// src/lib/components/AutoplayVideo.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	const { src, type = 'video/mp4' } = $props();
	let videoElement: HTMLVideoElement;

	onMount(() => {
		if (videoElement) {
			videoElement.addEventListener('loadedmetadata', () => {
				videoElement.play().catch(() => {
					// silently ignore
				});
			});
		}
	});
</script>

<video bind:this={videoElement} autoplay loop playsinline muted class="m-0 border-none">
	<source {src} {type} />
	Your browser does not support the video tag.
</video>

// src/components/AutoPlayVideo/AutoPlayVideo.tsx
import { useEffect, useRef } from "react";
import { SkeletonLoader } from "@components/SkeletonLoader/SkeletonLoader";

interface Props {
  src: string;
}

export const AutoPlayVideo: React.FC<Props> = ({ src }) => {
  const ref = useRef<HTMLVideoElement>(null);

  useEffect(() => {
    const autoPlay = async () => {
      if (ref.current && ref.current.readyState > 0) {
        try {
          await ref.current.play();
        } catch (err) {
          ref.current.controls = true;
        }
      }
    };
    autoPlay();
  }, []);

  return (
    <>
      <SkeletonLoader />
      <video ref={ref} autoPlay loop playsInline muted>
        <source src={src}></source>
      </video>
    </>
  );
};
